[versions]
discord = "aliucord-SNAPSHOT"
aliucord = "main-SNAPSHOT"
#noinspection GradleDependency
kotlin = "2.0.21"
android = "7.4.2"
ktlintPlugin = "12.1.1"
#noinspection GradleDependency Newer versions incompatible with other plugins
ktlint = "0.50.0"

[libraries]
discord = { module = "com.discord:discord", version.ref = "discord" }
aliucord = { module = "com.aliucord:Aliucord", version.ref = "aliucord" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
aliucord = { id = "com.aliucord.gradle", version.ref = "aliucord" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }